webtalk_init -webtalk_dir /home/vovan/Documents/GitHub/AXI_Lite_UVM_Agent/axi_lite_slave/axi_lite_slave.sim/sim_1/behav/xsim/xsim.dir/slave_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov  3 06:32:27 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "97255fc7-19df-4a76-8c8a-07455d2900f0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b9d05c9fafb74453a801661943d617c7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2550K CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3032.837 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3126 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "73" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.24_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "145044_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1331451 -regid "" -xml /home/vovan/Documents/GitHub/AXI_Lite_UVM_Agent/axi_lite_slave/axi_lite_slave.sim/sim_1/behav/xsim/xsim.dir/slave_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/vovan/Documents/GitHub/AXI_Lite_UVM_Agent/axi_lite_slave/axi_lite_slave.sim/sim_1/behav/xsim/xsim.dir/slave_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/vovan/Documents/GitHub/AXI_Lite_UVM_Agent/axi_lite_slave/axi_lite_slave.sim/sim_1/behav/xsim/xsim.dir/slave_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
